# Generated by Django 5.2.4 on 2025-07-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_experience_skill_testimonial_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma-separated list of technologies', max_length=300),
        ),
    ]
