# Generated by Django 5.1.4 on 2025-07-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_tech_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Resume', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the resume')),
                ('file', models.FileField(help_text='Upload PDF, DOC, or DOCX file', upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True, help_text='Mark as active resume for download')),
                ('version', models.CharField(blank=True, help_text='Version number or date', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
