# Generated by Django 5.1.4 on 2025-07-25 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
