# Generated by Django 5.1.4 on 2025-07-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contactsubmission_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
