# Generated by Django 5.1.4 on 2025-08-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_contactsubmission_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile image of the person giving testimonial', null=True, upload_to='testimonials/'),
        ),
    ]
