# Generated by Django 5.1.4 on 2025-08-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='approved',
            field=models.BooleanField(default=False, help_text='Mark as approved testimonial'),
        ),
    ]
